version: "3.4"

services:
  worklist:
    build:
      context: .
    image: worklist:v1
    container_name: worklist
    hostname: worklist
    command: bash container/inst.sh
    environment:
      - LEVEL=dev
      - POSTGRES_USER=admin_blog
      - POSTGRES_PASSWORD=admin_blog
      - POSTGRES_DB=db_blog_development
    ports:
      - 5499:5432
      - 4003:3000
    volumes:
      - ./:/app
