default: &default
  adapter: postgresql
  encoding: utf8
  username: admin
  database: admin
  password: admin
  port:     5432
  host: 0.0.0.0
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: db_development

test:
  <<: *default
  database: db_test

production:
  encoding: utf8
  username: hyfhpkuapmdkcl
  database: dassigqf8uvqj0
  password: 27b3e74e6f6468e7a0671f50a31f69a471b6d3a68533ef1da084282eb2ffa380
  adapter:  postgresql
  timeout:  5000
  host:     ec2-54-75-102-122.eu-west-1.compute.amazonaws.com
  port:     5432
  pool:     5
