default: &default
  adapter: postgresql
  encoding: utf8
  username: admin
  database: admin
  password: admin
  port:     5432
  host: 0.0.0.0
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: db_development

test:
  <<: *default
  database: db_test

production:
  encoding: utf8
  username: wzcpnsxtfprhwm
  database: d4pma7ig5csq0f
  password: 33b6a538b6d6378c38a264ecb5818c09fdf315c2697f6072d918b683bde6f9c1
  adapter:  postgresql
  timeout:  5000
  host:     ec2-63-32-7-190.eu-west-1.compute.amazonaws.com
  port:     5432
  pool:     5
