default: &default
  adapter: postgresql
  encoding: utf8
  username: admin
  database: admin
  password: admin
  port:     5432
  host: 0.0.0.0
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: db_development

test:
  <<: *default
  database: db_test

production:
  encoding: utf8
  username: ybzdysaesoovar
  database: ddtki22t0iqtk5
  password: fc36010dbf0f8b34514579c5b060d77635d0fbc83405f9c15122d1cea2155a42
  adapter:  postgresql
  timeout:  5000
  host:     ec2-54-228-218-84.eu-west-1.compute.amazonaws.com
  port:     5432
  pool:     5
